DROP TABLE PASSWORD_TOKEN CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE SATISFACTION_OF_A_LECTURE CASCADE CONSTRAINTS;
DROP TABLE COMMUTE CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE DEVICE_LOG CASCADE CONSTRAINTS;
DROP TABLE ATTEND_UPDATE_FILE CASCADE CONSTRAINTS;
DROP TABLE ATTEND_UPDATE CASCADE CONSTRAINTS;
DROP TABLE ATTEND CASCADE CONSTRAINTS;
DROP TABLE VACATION_APPLICATION CASCADE CONSTRAINTS;
DROP TABLE CONSULTATION CASCADE CONSTRAINTS;
DROP TABLE COUNSEL_APPLICATION CASCADE CONSTRAINTS;
DROP TABLE NOTICE_FILE CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE LECTURE_DATE CASCADE CONSTRAINTS;
DROP TABLE LECTURE_CONTROL CASCADE CONSTRAINTS;
DROP TABLE CLASS_STUDENT CASCADE CONSTRAINTS;
DROP TABLE CLASS_LECTURE CASCADE CONSTRAINTS;
DROP TABLE LECTURE CASCADE CONSTRAINTS;
DROP TABLE CLASS CASCADE CONSTRAINTS;
DROP TABLE DEVICE_RENT_ATT CASCADE CONSTRAINTS;
DROP TABLE DEVICE CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE LECTURE_DATE_APPROVAL CASCADE CONSTRAINTS;
-----------------------------------------------------------
DROP SEQUENCE SEQ_PTNO;
DROP SEQUENCE SEQ_QNO;
DROP SEQUENCE SEQ_SLNO;
DROP SEQUENCE SEQ_CMNO;
DROP SEQUENCE SEQ_DRANO;
DROP SEQUENCE SEQ_GNO;
DROP SEQUENCE SEQ_NFNO;
DROP SEQUENCE SEQ_ANO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_VANO;
DROP SEQUENCE SEQ_CLNO;
DROP SEQUENCE SEQ_CSNO;
DROP SEQUENCE SEQ_CCNO;
DROP SEQUENCE SEQ_AUFNO;
DROP SEQUENCE SEQ_AUNO;
DROP SEQUENCE SEQ_DLNO;
DROP SEQUENCE SEQ_LDNO;
DROP SEQUENCE SEQ_LCNO;
DROP SEQUENCE SEQ_CNO;
DROP SEQUENCE SEQ_NCNO;
DROP SEQUENCE SEQ_LNO;
DROP SEQUENCE SEQ_CANO;
DROP SEQUENCE SEQ_DNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_LDANO;

----------------------------------------------------------------
-- 1) SEQUENCES
-- (사용자는 INSERT 시 SEQ_XXX.NEXTVAL 사용)
----------------------------------------------------------------
CREATE SEQUENCE SEQ_MNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 멤버번호
CREATE SEQUENCE SEQ_DNO START WITH 1 INCREMENT BY 1 NOCACHE; --기자재번호
CREATE SEQUENCE SEQ_CANO START WITH 1 INCREMENT BY 1 NOCACHE; --상담번호
CREATE SEQUENCE SEQ_LNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 수업번호
CREATE SEQUENCE SEQ_NCNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 알림번호
CREATE SEQUENCE SEQ_CNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 상담번호
CREATE SEQUENCE SEQ_LCNO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LDNO START WITH 1 INCREMENT BY 1 NOCACHE; --수업일정번호
CREATE SEQUENCE SEQ_DLNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 기자재배정이력번호
CREATE SEQUENCE SEQ_AUNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 출결정정신청번호
CREATE SEQUENCE SEQ_AUFNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 출석정정신청파일번호
CREATE SEQUENCE SEQ_CCNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 반번호
CREATE SEQUENCE SEQ_CSNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 학생번호
CREATE SEQUENCE SEQ_CLNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 수업배정번호
CREATE SEQUENCE SEQ_VANO START WITH 1 INCREMENT BY 1 NOCACHE; -- 휴가신청번호
CREATE SEQUENCE SEQ_NNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 공지사항번호
CREATE SEQUENCE SEQ_ANO START WITH 1 INCREMENT BY 1 NOCACHE; -- 출석번호
CREATE SEQUENCE SEQ_NFNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 공지사항파일번호
CREATE SEQUENCE SEQ_GNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 성적번호
CREATE SEQUENCE SEQ_DRANO START WITH 1 INCREMENT BY 1 NOCACHE; -- 기자재대여신청번호
CREATE SEQUENCE SEQ_CMNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 근태번호
CREATE SEQUENCE SEQ_SLNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 강의만족ㄷㅎ번호
CREATE SEQUENCE SEQ_QNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 문의번호
CREATE SEQUENCE SEQ_PTNO START WITH 1 INCREMENT BY 1 NOCACHE; -- 비밀번호토큰번호
CREATE SEQUENCE SEQ_LDANO START WITH 1 INCREMENT BY 1 NOCACHE;

----------------------------------------------------------------
-- 2) MEMBER (가장 기본 테이블 — 다른 테이블이 참조)
----------------------------------------------------------------
CREATE TABLE MEMBER (
    MEMBER_NO     NUMBER PRIMARY KEY,
    MEMBER_ID     VARCHAR2(50) UNIQUE NOT NULL,
    MEMBER_NAME   VARCHAR2(50) NOT NULL,
    MEMBER_PASSWORD VARCHAR2(200) NOT NULL,
    CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE   DATE,
    STATUS        CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('N','Y')) NOT NULL,
    EMAIL         VARCHAR2(100),
    PHONE         VARCHAR2(100),
    ROLE          VARCHAR2(20) CHECK (ROLE IN ('ADMIN','TEACHER','STUDENT')) NOT NULL,
    BIRTH_DATE    DATE,
    VAC_CNT       NUMBER DEFAULT 0 NOT NULL
);


COMMENT ON COLUMN MEMBER.MEMBER_NO IS '시퀀스 SEQ_MNO로 생성';
COMMENT ON COLUMN MEMBER.STATUS IS 'N : 비활성, Y : 활성';
COMMENT ON COLUMN MEMBER.ROLE IS 'ADMIN, TEACHER, STUDENT';


----------------------------------------------------------------
-- 3) DEVICE (기자재)
----------------------------------------------------------------
CREATE TABLE DEVICE (
    DEVICE_ID    NUMBER PRIMARY KEY,
    DEVICE_KIND  VARCHAR2(30) UNIQUE NOT NULL,
    DEVICE_COUNT NUMBER DEFAULT 0 NOT NULL,
    STATUS       VARCHAR2(20) DEFAULT 'NORMAL' CHECK (STATUS IN ('NORMAL','BROKEN','RENTED','REPAIR','LOST'))
);
ALTER TABLE DEVICE ADD (DEVICE_REMAIN NUMBER DEFAULT 0);
ALTER TABLE DEVICE
ADD CONSTRAINT chk_device_remain CHECK (DEVICE_REMAIN >= 0);

COMMENT ON COLUMN DEVICE.DEVICE_ID IS '시퀀스 SEQ_DNO로 생성';
COMMENT ON COLUMN DEVICE.STATUS IS 'NORMAL, BROKEN, RENTED, REPAIR, LOST';

----------------------------------------------------------------
-- 4) DEVICE_RENT_ATT (기자재 대여 이력)
----------------------------------------------------------------
CREATE TABLE DEVICE_RENT_ATT (
    RENT_ATT_NO  NUMBER PRIMARY KEY,
    DEVICE_ID    NUMBER NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    CREATE_DATE  DATE DEFAULT SYSDATE NOT NULL,
    START_DATE   DATE NOT NULL,
    END_DATE     DATE NOT NULL,
    UPDATE_DATE  DATE,
    ATTEND_COUNT NUMBER DEFAULT 1 NOT NULL,
    STATUS       VARCHAR2(20) DEFAULT 'WAIT' CHECK (STATUS IN ('WAIT','APPROVAL','RETURN')),
    CONSTRAINT FK_DRA_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE (DEVICE_ID),
    CONSTRAINT FK_DRA_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN DEVICE_RENT_ATT.RENT_ATT_NO IS '시퀀스 SEQ_DRANO로 생성';

----------------------------------------------------------------
-- 5) CLASS (반/수업)
----------------------------------------------------------------
CREATE TABLE CLASS (
    CLASS_NO      NUMBER PRIMARY KEY,
    CLASS_NAME    VARCHAR2(100) UNIQUE NOT NULL,
    MEMBER_COUNT  NUMBER DEFAULT 0 NOT NULL,
    START_DATE    DATE DEFAULT SYSDATE NOT NULL,
    END_DATE      DATE NOT NULL
);


COMMENT ON COLUMN CLASS.CLASS_NO IS '시퀀스 SEQ_CCNO로 생성';

----------------------------------------------------------------
-- 6) LECTURE (강의/교과)
----------------------------------------------------------------
CREATE TABLE LECTURE (
    LECTURE_NO   NUMBER PRIMARY KEY,
    LECTURE_NAME VARCHAR2(100) NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    CONSTRAINT FK_LECTURE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN LECTURE.LECTURE_NO IS '시퀀스 SEQ_LNO로 생성';
COMMENT ON COLUMN LECTURE.MEMBER_NO IS '강사 MEMBER_NO (SEQ_MNO)';


----------------------------------------------------------------
-- 7) CLASS_LECTURE (반에 배정된 강의)
----------------------------------------------------------------
CREATE TABLE CLASS_LECTURE (
    CLASS_LECTURE_NO NUMBER PRIMARY KEY,
    CLASS_NO         NUMBER NOT NULL,
    LECTURE_NO       NUMBER NOT NULL,
    CLASS_DESC       VARCHAR2(200),
    PLAN_START_DATE  DATE,
    PLAN_END_DATE    DATE,
    CONSTRAINT FK_CL_CLASS FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO),
    CONSTRAINT FK_CL_LECTURE FOREIGN KEY (LECTURE_NO) REFERENCES LECTURE (LECTURE_NO)
);

COMMENT ON COLUMN CLASS_LECTURE.CLASS_LECTURE_NO IS '시퀀스 SEQ_CLNO로 생성';


----------------------------------------------------------------
-- 8) CLASS_STUDENT (반 학생 매핑)
----------------------------------------------------------------
CREATE TABLE CLASS_STUDENT (
    STUDENT_NO NUMBER PRIMARY KEY,
    CLASS_NO   NUMBER NOT NULL,
    MEMBER_NO  NUMBER NOT NULL,
    CONSTRAINT FK_CS_CLASS FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO),
    CONSTRAINT FK_CS_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN CLASS_STUDENT.STUDENT_NO IS '시퀀스 SEQ_CSNO로 생성';



----------------------------------------------------------------
-- 9) LECTURE_CONTROL (수업 세션/관리)
----------------------------------------------------------------
CREATE TABLE LECTURE_CONTROL (
    CONTROLL_NO      NUMBER PRIMARY KEY,
    CLASS_LECTURE_NO NUMBER NOT NULL,
    PLAN_DATE        DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LC_CLASS_LECTURE FOREIGN KEY (CLASS_LECTURE_NO) REFERENCES CLASS_LECTURE (CLASS_LECTURE_NO)
);

COMMENT ON COLUMN LECTURE_CONTROL.CONTROLL_NO IS '시퀀스 SEQ_LCNO로 생성';



----------------------------------------------------------------
-- 10) LECTURE_DATE (수업 일정 / 휴강)
----------------------------------------------------------------
CREATE TABLE LECTURE_DATE (
    LECTURE_DATE_NO NUMBER PRIMARY KEY,
    START_DATE      DATE DEFAULT SYSDATE NOT NULL,
    END_DATE        DATE NOT NULL,
    TITLE           VARCHAR2(50) NOT NULL,
    CONTENT         CLOB NOT NULL,
    CLASS_LECTURE_NO NUMBER NOT NULL,
    DATE_TYPE       VARCHAR2(20) DEFAULT 'CLASS' CHECK (DATE_TYPE IN ('CLASS','OFF')) NOT NULL,
    CONSTRAINT FK_LD_CLASS_LECTURE FOREIGN KEY (CLASS_LECTURE_NO) REFERENCES CLASS_LECTURE (CLASS_LECTURE_NO)
);

COMMENT ON COLUMN LECTURE_DATE.LECTURE_DATE_NO IS '시퀀스 SEQ_LDNO로 생성';

----------------------------------------------------------------
-- 11) NOTIFICATION (알림)
----------------------------------------------------------------
CREATE TABLE NOTIFICATION (
    NOTIFICATION_NO NUMBER PRIMARY KEY,
    NOTIFICATION_TITLE VARCHAR2(50) NOT NULL,
    NOTIFICATION_CONTENTS CLOB NOT NULL,
    NOTIFICATION_BOOLEAN CHAR(1) DEFAULT 'N' CHECK (NOTIFICATION_BOOLEAN IN ('N','Y')) NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    CONSTRAINT FK_NOTIFICATION_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_NO IS '시퀀스 SEQ_NCNO로 생성';


----------------------------------------------------------------
-- 12) NOTICE (공지사항)
-- NOTE: CLASS_NO NULL이면 전체공지로 처리 (따라서 NULL 허용)
----------------------------------------------------------------
CREATE TABLE NOTICE (
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_CONTENTS CLOB NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE,
    MEMBER_NO NUMBER NOT NULL,
    CLASS_NO NUMBER,
    NOTICE_TYPE VARCHAR2(20) CHECK (NOTICE_TYPE IN ('ALL','CLASS','SYSTEM','EVENT')),
    CONSTRAINT FK_NOTICE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT FK_NOTICE_CLASS FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO)
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '시퀀스 SEQ_NNO로 생성';
COMMENT ON COLUMN NOTICE.CLASS_NO IS 'NULL이면 전체공지';


----------------------------------------------------------------
-- 13) NOTICE_FILE (공지 파일)
----------------------------------------------------------------
CREATE TABLE NOTICE_FILE (
    NOTICE_FILE_NO NUMBER PRIMARY KEY,
    NOTICE_FILE_ORI_NAME VARCHAR2(50) NOT NULL,
    NOTICE_FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    NOTICE_NO NUMBER NOT NULL,
    CONSTRAINT FK_NOTICE_FILE_NOTICE FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE (NOTICE_NO)
);

COMMENT ON COLUMN NOTICE_FILE.NOTICE_FILE_NO IS '시퀀스 SEQ_NFNO로 생성';

----------------------------------------------------------------
-- 14) COUNSEL_APPLICATION (상담 신청)
-- 설계: 신청은 MEMBER(신청자) 참조, COUNSELOR_NO는 상담사 MEMBER_NO(선택)로 두고
-- CONSULTATION(상담완료) 테이블이 별도로 상세 기록을 가짐. (순환참조 제거)
----------------------------------------------------------------
CREATE TABLE COUNSEL_APPLICATION (
    COUNSEL_APPLICATION_NO NUMBER PRIMARY KEY,
    COUNSEL_CONTENT VARCHAR2(200),
    COUNSEL_DATE TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'REQUESTED' CHECK (STATUS IN ('REQUESTED','APPROVED','REJECTED','DONE')) NOT NULL,
    REFUSAL VARCHAR2(200),
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    COUNSELOR_NO NUMBER, -- 상담 담당자(member) : nullable until assigned
    COUNSEL_MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT FK_CA_COUNSELER_MEMBER FOREIGN KEY (COUNSELOR_NO) REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT FK_CA_MEMBER FOREIGN KEY (COUNSEL_MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN COUNSEL_APPLICATION.COUNSEL_APPLICATION_NO IS '시퀀스 SEQ_CANO로 생성';



----------------------------------------------------------------
-- 15) CONSULTATION (상담 기록) — COUNSEL_APPLICATION을 참조
----------------------------------------------------------------
CREATE TABLE CONSULTATION (
    CONSULTATION_NO NUMBER PRIMARY KEY,
    CONSULTATION_CONTENT CLOB NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    COUNSEL_APPLICATION_NO NUMBER NOT NULL,
    CONSTRAINT FK_CONSULT_CA FOREIGN KEY (COUNSEL_APPLICATION_NO) REFERENCES COUNSEL_APPLICATION (COUNSEL_APPLICATION_NO)
);

COMMENT ON COLUMN CONSULTATION.CONSULTATION_NO IS '시퀀스 SEQ_CNO로 생성';



----------------------------------------------------------------
-- 16) VACATION_APPLICATION (휴가 신청)
----------------------------------------------------------------
CREATE TABLE VACATION_APPLICATION (
    VACATION_APPLICATION_NO NUMBER PRIMARY KEY,
    VACATION_START_DATE DATE DEFAULT SYSDATE NOT NULL,
    VACATION_END_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'REQUESTED' CHECK (STATUS IN ('REQUESTED','APPROVED','REJECTED')) NOT NULL,
    REFUSAL VARCHAR2(200),
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    LECTURE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT FK_VA_LECTURE FOREIGN KEY (LECTURE_NO) REFERENCES LECTURE (LECTURE_NO),
    CONSTRAINT FK_VA_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN VACATION_APPLICATION.VACATION_APPLICATION_NO IS '시퀀스 SEQ_VANO로 생성';


----------------------------------------------------------------
-- 17) ATTEND (출결)
----------------------------------------------------------------
CREATE TABLE ATTEND (
    ATTEND_NO NUMBER PRIMARY KEY,
    ATTEND_STATUS VARCHAR2(20) CHECK (ATTEND_STATUS IN ('ATTEND','LATE','LEAVE_EARLY','ABSENT')) NOT NULL,
    ATTEND_DATE DATE DEFAULT SYSDATE NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    SESSION_NO NUMBER NOT NULL,
    STUDENT_NO NUMBER NOT NULL,
    CONSTRAINT FK_ATTEND_SESSION FOREIGN KEY (SESSION_NO) REFERENCES LECTURE_CONTROL (CONTROLL_NO),
    CONSTRAINT FK_ATTEND_STUDENT FOREIGN KEY (STUDENT_NO) REFERENCES CLASS_STUDENT (STUDENT_NO)
);

COMMENT ON COLUMN ATTEND.ATTEND_NO IS '시퀀스 SEQ_ANO로 생성';



----------------------------------------------------------------
-- 18) ATTEND_UPDATE (출결 정정 신청)
----------------------------------------------------------------
CREATE TABLE ATTEND_UPDATE (
    ATTEND_UPDATE_NO NUMBER PRIMARY KEY,
    ATTEND_UPDATE_CONTENT VARCHAR2(200) NOT NULL,
    CORRECTION_APPLICATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'REQUESTED' CHECK (STATUS IN ('REQUESTED','APPROVED','REJECTED')) NOT NULL,
    REFUSAL VARCHAR2(200),
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    APPROVER_MEMBER_NO NUMBER, -- 관리자/심사자 (nullable until assigned)
    ATTEND_NO NUMBER NOT NULL,
    ATTEND_STATUS VARCHAR2(20) CHECK (ATTEND_STATUS IN ('ATTEND','LATE','LEAVE_EARLY','ABSENT')) NOT NULL,
    CONSTRAINT FK_AU_APPROVER FOREIGN KEY (APPROVER_MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT FK_AU_ATTEND FOREIGN KEY (ATTEND_NO) REFERENCES ATTEND (ATTEND_NO)
);

COMMENT ON COLUMN ATTEND_UPDATE.ATTEND_UPDATE_NO IS '시퀀스 SEQ_AUNO로 생성';



----------------------------------------------------------------
-- 19) ATTEND_UPDATE_FILE (출결 정정 첨부파일)
----------------------------------------------------------------
CREATE TABLE ATTEND_UPDATE_FILE (
    ATTEND_UPDATE_FILE_NO NUMBER PRIMARY KEY,
    ATTEND_UPDATE_NO NUMBER NOT NULL,
    ATTEND_UPDATE_FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE,
    ATTEND_UPDATE_FILE_ORI_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_AUF_AU FOREIGN KEY (ATTEND_UPDATE_NO) REFERENCES ATTEND_UPDATE (ATTEND_UPDATE_NO)
);

COMMENT ON COLUMN ATTEND_UPDATE_FILE.ATTEND_UPDATE_FILE_NO IS '시퀀스 SEQ_AUFNO로 생성';


----------------------------------------------------------------
-- 20) DEVICE_LOG (기자재 대여/반납 이력)
----------------------------------------------------------------
CREATE TABLE DEVICE_LOG (
    DEVICE_LOG_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    RENT_ATT_NO NUMBER NOT NULL,
    DEVICE_CNT NUMBER DEFAULT 0 NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    RETURN_DATE DATE,
    CONSTRAINT FK_DL_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT FK_DL_RENT FOREIGN KEY (RENT_ATT_NO) REFERENCES DEVICE_RENT_ATT (RENT_ATT_NO)
);

COMMENT ON COLUMN DEVICE_LOG.DEVICE_LOG_NO IS '시퀀스 SEQ_DLNO로 생성';


----------------------------------------------------------------
-- 21) GRADE (성적)
----------------------------------------------------------------
CREATE TABLE GRADE (
    GRADE_NO NUMBER PRIMARY KEY,
    GRADE NUMBER DEFAULT 0 NOT NULL,
    CLASS_LECTURE_NO NUMBER NOT NULL,
    STUDENT_NO NUMBER NOT NULL,
    TEST_NAME VARCHAR2(200) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_GRADE_CLASSLEC FOREIGN KEY (CLASS_LECTURE_NO) REFERENCES CLASS_LECTURE (CLASS_LECTURE_NO),
    CONSTRAINT FK_GRADE_STUDENT FOREIGN KEY (STUDENT_NO) REFERENCES CLASS_STUDENT (STUDENT_NO)
);

COMMENT ON COLUMN GRADE.GRADE_NO IS '시퀀스 SEQ_GNO로 생성';



----------------------------------------------------------------
-- 22) COMMUTE (근태)
----------------------------------------------------------------
CREATE TABLE COMMUTE (
    COMMUTE_NO NUMBER PRIMARY KEY,
    COMMUTE_STATUS VARCHAR2(20) CHECK (COMMUTE_STATUS IN ('IN','OUT','LATE','HALF','VACATION')) NOT NULL,
    COMMUTE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT FK_COMMUTE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN COMMUTE.COMMUTE_NO IS '시퀀스 SEQ_CMNO로 생성';



----------------------------------------------------------------
-- 23) SATISFACTION_OF_A_LECTURE (강의 만족도)
----------------------------------------------------------------
CREATE TABLE SATISFACTION_OF_A_LECTURE (
    SATISFACTION_NO NUMBER PRIMARY KEY,
    SUGGESTION CLOB,
    CREATE_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE NOT NULL,
    CLASS_LECTURE_NO NUMBER NOT NULL,
    STUDENT_NO NUMBER NOT NULL,
    CONSTRAINT FK_SAT_CLASSLEC FOREIGN KEY (CLASS_LECTURE_NO) REFERENCES CLASS_LECTURE (CLASS_LECTURE_NO),
    CONSTRAINT FK_SAT_STUDENT FOREIGN KEY (STUDENT_NO) REFERENCES CLASS_STUDENT (STUDENT_NO)
);

ALTER TABLE SATISFACTION_OF_A_LECTURE ADD CLASS_RATING NUMBER NOT NULL CHECK (CLASS_RATING BETWEEN 1 AND 5);
        
ALTER TABLE SATISFACTION_OF_A_LECTURE ADD LECTURE_RATING NUMBER NOT NULL CHECK (LECTURE_RATING BETWEEN 1 AND 5);

COMMENT ON COLUMN SATISFACTION_OF_A_LECTURE.SATISFACTION_NO IS '시퀀스 SEQ_SLNO로 생성';



----------------------------------------------------------------
-- 24) QUESTION (문의)
----------------------------------------------------------------
CREATE TABLE QUESTION (
    QUESTION_NO NUMBER PRIMARY KEY,
    QUESTION_TYPE VARCHAR2(20) CHECK (QUESTION_TYPE IN ('COURSE','SYSTEM','ETC')) NOT NULL,
    QUESTION_CONTENT CLOB NOT NULL,
    ANSWER CLOB,
    QUESTION_MEMBER NUMBER NOT NULL,
    ANSWER_MEMBER NUMBER,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    CONSTRAINT FK_QUESTION_QUESTIONER FOREIGN KEY (QUESTION_MEMBER) REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT FK_QUESTION_ANSWERER FOREIGN KEY (ANSWER_MEMBER) REFERENCES MEMBER (MEMBER_NO)
);
ALTER TABLE QUESTION ADD QUESTION_TITLE VARCHAR2(100) NOT NULL;

COMMENT ON COLUMN QUESTION.QUESTION_NO IS '시퀀스 SEQ_QNO로 생성';



----------------------------------------------------------------
-- 25) PASSWORD_TOKEN (비밀번호 찾기/인증 토큰)
----------------------------------------------------------------
CREATE TABLE PASSWORD_TOKEN (
    PASSWORD_TOKEN_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    TOKEN VARCHAR2(200) NOT NULL,
    END_DATE TIMESTAMP DEFAULT (SYSTIMESTAMP + INTERVAL '30' MINUTE),
    STATUS VARCHAR2(20) DEFAULT 'ORDER' NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT CHK_PT_STATUS CHECK (STATUS IN ('ORDER', 'USED')),
    CONSTRAINT FK_PT_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN PASSWORD_TOKEN.PASSWORD_TOKEN_NO IS '시퀀스 SEQ_PTNO로 생성';

CREATE TABLE LECTURE_DATE_APPROVAL (
   APPROVAL_NO       NUMBER          NOT NULL,
   APPROVED_BY       NUMBER          NULL,
   APPROVAL_REJECT   VARCHAR2(200)   NULL,
   APPROVAL_DATE      DATE          DEFAULT SYSDATE NOT NULL,
   LECTURE_DATE_NO   NUMBER          NOT NULL,
   STATUS           VARCHAR2(20)    DEFAULT 'IN_PROGRESS' CHECK (STATUS IN ('IN_PROGRESS','APPROVED','REJECTED')) NOT NULL,
    
    CONSTRAINT PK_LDA PRIMARY KEY (APPROVAL_NO),
    CONSTRAINT FK_LDA_LDATE FOREIGN KEY (LECTURE_DATE_NO) REFERENCES LECTURE_DATE(LECTURE_DATE_NO) ON DELETE CASCADE
);
----------------------------------------------------------------
-- 26) 마무리: COMMIT
----------------------------------------------------------------


COMMIT;

